# =============================================================================
# 02-fit-survival.R
# Parametric Survival Model Fitting
# Candidates: Exponential, Weibull, Log-normal, Log-logistic,
#             Gompertz, Generalised Gamma
#
# Input:  data/processed/ipd_dfs.rds
#         data/processed/ipd_os.rds
#
# Output: data/processed/survival_fits_dfs.rds
#         data/processed/survival_fits_os.rds
#         output/tables/aic_bic_comparison.csv
#         output/figures/survival_fit_dfs.pdf
#         output/figures/survival_fit_os.pdf
#
# Packages: flexsurv, stats, dplyr
# =============================================================================
#
# REFERENCE CODE PROVENANCE:
#   Parametric distribution selection workflow: NICE DSU TSD 14 (Latimer NR,
#     2013). "Survival analysis for economic evaluations alongside clinical
#     trials: extrapolation with patient-level data." NICE Decision Support
#     Unit Technical Support Document 14. Six-distribution candidate set,
#     AIC/BIC ranking, visual inspection of extrapolated tails, and clinical
#     plausibility checks against external mortality follow Sections 4.3-4.6.
#   flexsurv R package: Jackson CH (2016). "flexsurv: A Platform for
#     Parametric Survival Modeling in R." Journal of Statistical Software
#     70(8):1-33. DOI 10.18637/jss.v70.i08. flexsurvreg() with dist =
#     "exp"|"weibull"|"lnorm"|"llogis"|"gompertz"|"gengamma" is the
#     reference implementation for all six candidate distributions.
#   Treatment effect application S_int(t) = S_ctrl(t)^HR for AFT base case:
#     standard NICE TSD 14 practice (Section 4.4); the exact-only-under-PH
#     caveat is discussed in the thesis Methods chapter (Survival Data
#     subsection).
#   Long-term mortality cap against general population: NICE DSU TSD 21
#     (Rutherford et al. 2020). "Flexible methods for survival analysis."
#     NICE Decision Support Unit TSD 21. The pmin/hazard_max approaches
#     used in 03-build-psm.R follow this guidance.
#
# Adaptations:
#   1. Per-arm fitting (control arm only via flexsurvreg, intervention arm
#      derived via S_int(t) = S_ctrl(t)^HR in 03-build-psm.R) replaces the
#      pooled-with-treatment-covariate approach. This separates the
#      "data-driven baseline distribution" choice from the "constant HR"
#      treatment effect assumption.
#   2. Defensive validation of IPD input structure before fitting;
#      not present in flexsurv vignettes.
#   3. AIC/BIC tables exported to CSV (output/tables/aic_bic_comparison.csv)
#      for thesis Appendix A.2 reproduction.
#
# Academic citations:
#   Latimer NR (2013). NICE DSU Technical Support Document 14: Survival
#     analysis for economic evaluations alongside clinical trials.
#   Jackson CH (2016). DOI 10.18637/jss.v70.i08.
#   Rutherford MJ, Lambert PC, Sweeting MJ, Pennington B, Crowther MJ,
#     Abrams KR, Latimer NR (2020). NICE DSU Technical Support Document 21.
# =============================================================================

# Requires IPD from 01-digitize-km.R (generated by running that script first)

# Candidate distributions for flexsurvreg
# GUIDELINE: NICE TSD 14/19 (supplementary  --  DMP/NOMA has no equivalent
# parametric fitting methodology guidance). Fit all plausible parametric
# families, select by AIC/BIC plus clinical plausibility of extrapolation.
#
# DISCLOSURE (S^HR on AFT base case): Treatment effect application uses
# S_int(t) = S_ctrl(t)^HR. This is EXACT for proportional hazards (PH)
# distributions: exp, weibull, gompertz. For non-PH distributions (lnorm,
# llogis, gengamma) the operation is an approximation: AFT models have a
# time-varying instantaneous HR, so applying a constant Cox HR yields a
# survival curve that is not a member of any standard parametric family.
# The base case uses the BIC-selected log-normal (an AFT distribution), so
# the S^HR application is approximate. This is the standard NICE TSD 14
# convention (Latimer 2013, Section 4.4) and is disclosed in the thesis
# Methods chapter under "Survival Data" alongside the parametric model
# selection text. The structural sensitivity analysis (06b-structural-sa.R)
# additionally tests generalised gamma for DFS (AFT, approximation), the
# only registered distribution scenario, so the impact of distribution
# choice on this assumption is reported in the published results.
# Reference: Latimer NR (2013), NICE DSU TSD 14, Section 4.4. Disclosure
#   documented in thesis Methods chapter (Survival Data subsection).
dist_candidates <- c(
  "exp",        # Exponential (constant hazard)  --  PH family
  # GUIDELINE: Include this family in the standard parametric survival candidate set (DMP 2026)
  "weibull",    # Weibull (monotone hazard)  --  PH family
  "lnorm",      # Log-normal  --  AFT family (S^HR is approximation)
  "llogis",     # Log-logistic  --  AFT family (S^HR is approximation)
  # GUIDELINE: Include this family in the standard parametric survival candidate set (DMP 2026)
  "gompertz",   # Gompertz (monotone hazard)  --  PH family
  "gengamma"    # Generalised gamma  --  AFT family (S^HR is approximation)
)

fit_distributions <- function(ipd, dist_list) {
  # ipd: data frame with columns 'time' and 'status' (1=event, 0=censored)
  #
  if (!is.data.frame(ipd)) {
    stop("fit_distributions: ipd must be a data frame. ",
         "Got class: ", paste(class(ipd), collapse = ", "))
  }
  if (!all(c("time", "status") %in% names(ipd))) {
    stop("fit_distributions: ipd must have columns 'time' and 'status'. ",
         "Found: ", paste(names(ipd), collapse = ", "))
  }
  if (nrow(ipd) == 0) {
    stop("fit_distributions: ipd has 0 rows. Cannot fit survival models.")
  }

  fits <- lapply(dist_list, function(d) {
    tryCatch(
      # GUIDELINE: Fit each candidate parametric survival model to pseudo-IPD with flexsurvreg (Jackson 2016)
      flexsurv::flexsurvreg(survival::Surv(time, status) ~ 1,
                            data = ipd, dist = d),
      error = function(e) {
        message("  Failed to fit: ", d, "  --  ", e$message)
        NULL
      }
    )
  })
  names(fits) <- dist_list
  Filter(Negate(is.null), fits)
}

compare_aic_bic <- function(fits) {
  if (length(fits) == 0) {
    warning("compare_aic_bic: no distributions converged. ",
            "Returning empty comparison table.")
    return(data.frame(distribution = character(0),
                      AIC = numeric(0),
                      BIC = numeric(0),
                      stringsAsFactors = FALSE))
  }
  # AIC() and BIC() from stats:: (auto-loaded in R).
  # Both are S3 generics that dispatch to flexsurv methods for flexsurvreg objects.
  data.frame(
    distribution = names(fits),
    # GUIDELINE: Compare candidate survival models using AIC before assessing extrapolation plausibility (Latimer 2013)
    AIC = sapply(fits, stats::AIC),
    # GUIDELINE: Compare candidate survival models using BIC before assessing extrapolation plausibility (Latimer 2013)
    BIC = sapply(fits, stats::BIC),
    stringsAsFactors = FALSE
  ) |>
    dplyr::arrange(AIC)
}

# --- Placeholder execution ---------------------------------------------------
# Survival architecture uses control-arm-only fitting. The main analysis fits
# the CONTROL ARM ONLY. The intervention arm survival is derived by
# applying HR to the control arm's cumulative hazard (standard PSM
# approach for trials reporting HRs). This ensures the deterministic
# and PSA analyses use the same treatment effect mechanism.
#
# Intervention arm fits are retained for VALIDATION ONLY  --  they can
# be overlaid on KM curves to visually verify that the HR-derived
# curves are consistent with the observed intervention arm data.
# They are NOT used as model inputs.

if (file.exists("data/processed/ipd_dfs.rds") &&
    file.exists("data/processed/ipd_os.rds")) {

  ipd_data <- list(
    dfs = readRDS("data/processed/ipd_dfs.rds"),
    os  = readRDS("data/processed/ipd_os.rds")
  )

  # =====================================================================
  # PRIMARY FITTING: Control arm only (used in the model)
  # =====================================================================
  message("Fitting DFS survival models (CONTROL ARM  --  primary)...")
  # Fit the DFS control arm to select the baseline survival distribution.
  fits_dfs_ctrl <- fit_distributions(ipd_data$dfs$control, dist_candidates)

  message("Fitting OS survival models (CONTROL ARM  --  primary)...")
  # Fit the OS control arm to select the baseline survival distribution.
  fits_os_ctrl <- fit_distributions(ipd_data$os$control, dist_candidates)

  # =====================================================================
  # VALIDATION ONLY: Intervention arm fits (NOT used in the model)
  # These are retained for visual overlay on KM curves to verify that
  # the HR-derived intervention curves match the observed data.
  # =====================================================================
  message("Fitting DFS survival models (INTERVENTION  --  validation only)...")
  fits_dfs_int <- fit_distributions(ipd_data$dfs$intervention, dist_candidates)

  message("Fitting OS survival models (INTERVENTION  --  validation only)...")
  fits_os_int <- fit_distributions(ipd_data$os$intervention, dist_candidates)

  # AIC/BIC comparison tables (control arm drives model selection)
  aic_dfs_ctrl <- compare_aic_bic(fits_dfs_ctrl)
  aic_os_ctrl  <- compare_aic_bic(fits_os_ctrl)
  # Validation tables (for comparison, not for model selection)
  aic_dfs_int  <- compare_aic_bic(fits_dfs_int)
  aic_os_int   <- compare_aic_bic(fits_os_int)

  write.csv(rbind(
    cbind(endpoint = "DFS", arm = "Standard Care (PRIMARY)",      aic_dfs_ctrl),
    cbind(endpoint = "OS",  arm = "Standard Care (PRIMARY)",      aic_os_ctrl),
    cbind(endpoint = "DFS", arm = "Exercise (VALIDATION)", aic_dfs_int),
    cbind(endpoint = "OS",  arm = "Exercise (VALIDATION)", aic_os_int)
  ), "output/tables/aic_bic_comparison.csv", row.names = FALSE)

  # Save control arm fits (input to the model)
  # The main script reads fits_dfs_ctrl and fits_os_ctrl
  saveRDS(fits_dfs_ctrl, "data/processed/survival_fits_dfs_ctrl.rds")
  saveRDS(fits_os_ctrl,  "data/processed/survival_fits_os_ctrl.rds")

  # Save intervention arm fits (validation only  --  clearly labelled)
  saveRDS(fits_dfs_int, "data/processed/survival_fits_dfs_int_validation.rds")
  saveRDS(fits_os_int,  "data/processed/survival_fits_os_int_validation.rds")

  # Legacy save for backward compatibility (contains both arms)
  fits_dfs <- list(control = fits_dfs_ctrl, intervention = fits_dfs_int)
  fits_os  <- list(control = fits_os_ctrl,  intervention = fits_os_int)
  saveRDS(fits_dfs, "data/processed/survival_fits_dfs.rds")
  saveRDS(fits_os,  "data/processed/survival_fits_os.rds")

  message("Survival fitting complete. Review AIC/BIC table at:",
          " output/tables/aic_bic_comparison.csv")
  message("PRIMARY fits: control arm only -> data/processed/survival_fits_*_ctrl.rds")
  message("VALIDATION fits: intervention arm -> data/processed/survival_fits_*_int_validation.rds")
  message("[INFO] Review AIC/BIC table and update best_dist_dfs/best_dist_os",
          " in 00-parameters.R if distributions change")

} else {
  message("[INFO] Run 01-digitize-km.R first to generate IPD data.")
}
